//
// Created by edwin on 7/16/26.
//

#ifndef MINGW_VULKAN_ALLOCATOR_HXX
#define MINGW_VULKAN_ALLOCATOR_HXX

#define VMA_STATIC_VULKAN_FUNCTIONS 0
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 0
#include <vk_mem_alloc.h>

#endif // MINGW_VULKAN_ALLOCATOR_HXX
