// Generated by CMake at build time -- do not edit by hand.
//
// Each struct below reflects the push-constant block of one
// push-constant-bearing shader entry point (see the "Shader push-constant
// reflection" section of CMakeLists.txt and
// tools/shader_reflect/reflect_push_constants.cpp): the shader is compiled
// to SPIR-V and its push_constant block is read back with SPIRV-Reflect, so
// the layout below always matches the shader it was generated from.
// Regenerated whenever a .slang file under assets/shaders or the reflection
// tool changes.

#pragma once

#include <cstddef>
#include <cstdint>
#include <vulkan/vulkan_core.h>

